### ISSUE TITLE
Issue running on macOS

### ISSUE THREAD

**Issue by rgoulter** [rgoulter/c-worksheet-instrumentor#2]
Running the unzipped tool as it downloaded on OSX yields the error below.

This is kindof annoying. + The tool isn't "robust" in the case where Java throws an exception like that. (i.e. Vim just hangs, which is quite unhelpful).

It seems running code from tmpdir is bad? (n.b. error also occurs from running `gradle test`, so..).

```
richardgoulter@r-7-105-25-172  ~/.vim/bundle/c-worksheet.vim/tool/cworksheet-proguard-0.2.4/bin$ ./c-worksheetify ~/hello.c
Exception in thread "main" java.io.IOException: Cannot run program "/var/folders/yt/xblbjsj91g3fh7_mqq0n2rn00000gn/T/cworksheet1178141796752375443.out": error=13, Permission denied
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
    at scala.i.a.o.a(Unknown Source)
    at edu.nus.worksheet.Worksheetify$.a(Unknown Source)
    at edu.nus.worksheet.Worksheetify.main(Unknown Source)
Caused by: java.io.IOException: error=13, Permission denied
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
    ... 3 more
```

**Comment by rgoulter** [comment]
`cat ~/hello.c | gcc -std=c99 -o /Users/richardgoulter/github/c-worksheet-instrumentor/cworksheet.out -fno-diagnostics-show-caret -fno-diagnostics-show-option -xc -`

Note that Clang doesn't have the `-fno-diagnostics-show-caret`.
